// sumber: desktop paperite/src/components/nav-main.tsx — jangan ngarang lagi
export const SPACE_COLORS = [
  '#f04438',
  '#fb6f24',
  '#f5b700',
  '#35c759',
  '#19b8a9',
  '#2f80ed',
  '#7c5cff',
  '#d946ef',
  '#ff4f86',
  '#e11d48',
  '#94a3b8',
  '#64748b',
  '#1e293b',
  '#f8fafc',
] as const;

// material symbols (google) ligature names — dirender via font MaterialSymbols_400Regular
// 18 pertama = mapping 1:1 dari desktop spaceIcons, sisanya buat scroll
export const SPACE_SYMBOLS = [
  'cloud',
  'folder',
  'work',
  'book',
  'lightbulb',
  'code',
  'diamond',
  'favorite',
  'psychology',
  'auto_awesome',
  'star',
  'music_note',
  'photo_camera',
  'bookmark',
  'bolt',
  'explore',
  'group',
  'push_pin',
  'inbox',
  'travel_explore',
  'school',
  'fitness_center',
  'nights_stay',
  'menu_book',
  'task_alt',
  'schedule',
  'palette',
  'rocket_launch',
  'sports_esports',
  'restaurant',
  'local_cafe',
  'directions_run',
  'calendar_month',
  'wallet',
  'headphones',
  'movie',
  'image',
  'mic',
  'newspaper',
  'shopping_bag',
  'language',
  'beach_access',
] as const;
